/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_MESSAGE_PB_H_INCLUDED
#define PB_MESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Message {
    bool has_temperature;
    float temperature;
    bool has_humidity;
    float humidity;
    bool has_pressure;
    float pressure;
    bool has_co_2;
    float co_2;
    bool has_voc;
    float voc;
    bool has_temperature_2;
    float temperature_2;
    bool has_humidity_2;
    float humidity_2;
    bool has_pressure_2;
    float pressure_2;
    bool has_co_2_2;
    float co_2_2;
    bool has_voc_2;
    float voc_2;
} Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Message_init_default                     {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define Message_init_zero                        {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Message_temperature_tag                  1
#define Message_humidity_tag                     2
#define Message_pressure_tag                     3
#define Message_co_2_tag                         4
#define Message_voc_tag                          5
#define Message_temperature_2_tag                6
#define Message_humidity_2_tag                   7
#define Message_pressure_2_tag                   8
#define Message_co_2_2_tag                       9
#define Message_voc_2_tag                        10

/* Struct field encoding specification for nanopb */
#define Message_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature,       1) \
X(a, STATIC,   OPTIONAL, FLOAT,    humidity,          2) \
X(a, STATIC,   OPTIONAL, FLOAT,    pressure,          3) \
X(a, STATIC,   OPTIONAL, FLOAT,    co_2,              4) \
X(a, STATIC,   OPTIONAL, FLOAT,    voc,               5) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature_2,     6) \
X(a, STATIC,   OPTIONAL, FLOAT,    humidity_2,        7) \
X(a, STATIC,   OPTIONAL, FLOAT,    pressure_2,        8) \
X(a, STATIC,   OPTIONAL, FLOAT,    co_2_2,            9) \
X(a, STATIC,   OPTIONAL, FLOAT,    voc_2,            10)
#define Message_CALLBACK NULL
#define Message_DEFAULT NULL

extern const pb_msgdesc_t Message_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Message_fields &Message_msg

/* Maximum encoded size of messages (where known) */
#define MESSAGE_PB_H_MAX_SIZE                    Message_size
#define Message_size                             50

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
